matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8
      before_script:
        - android list targets
        - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a --skin 480x800
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 6
      script: npm run test

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-21
    - android-25
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src